"""Supervised fine-tuning on agent trajectories.

Pretraining teaches the model the *language* of security. This teaches it the
*job*. They are different curricula and conflating them is why ``action-json``
scored 0/5: the pretraining corpus is 466M characters of security text in which
trajectories would be a rounding error, so diluting one with the other means the
task signal never gets a turn.

Two stages, in order:

1. **Pretrain** on everything. The model learns what a registry path looks like,
   what a CVSS vector is, that YAML nests, that PowerShell is Verb-Noun.
2. **Fine-tune** on trajectories alone, at a low learning rate, for a short run.
   The model learns that a task is answered by emitting ``<|act|>`` with JSON
   the registry accepts, reading ``<|obs|>``, and continuing.

**Loss is masked to the model's own turns.** A trajectory contains the task, the
catalogue, and the observations — none of which the model produces at serving
time. Training it to predict an observation teaches it to hallucinate tool
output, which is the single worst failure mode an agent can have: a model that
writes its own ``<|obs|>`` will confidently report findings about a machine it
never touched. Only the spans after ``<|act|>``, ``<|plan|>`` and ``<|find|>``
carry gradient. Everything else is context to condition on, not output to
imitate.

That masking is the whole reason this file exists rather than being three lines
of pretraining with a different dataset.
"""

from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
import numpy as np

from .config import TrainConfig
from .model import Whetstone
from .pretrain import cosine_lr, load_checkpoint, save_checkpoint

__all__ = ["build_examples", "sft"]

#: Segments whose content the model is responsible for producing. Everything
#: else in a trajectory is given to it, not generated by it.
_MODEL_TURNS = ("<|act|>", "<|plan|>", "<|find|>")


def build_examples(
    trajectory_dir: Path, tokenizer_path: Path, seq_len: int
) -> tuple[np.ndarray, np.ndarray]:
    """Tokenise trajectories into (inputs, loss_mask) padded to ``seq_len``.

    The mask is built by walking the token stream and flipping on at a model-turn
    marker, off at the next marker of any kind. Doing it in token space rather
    than character space avoids an off-by-one where a marker's own tokens fall on
    the wrong side of the boundary — which would train the model to predict the
    marker that *precedes* its turn instead of the content that follows it.
    """
    from tokenizers import Tokenizer

    tok = Tokenizer.from_file(str(tokenizer_path))
    marker_ids = {tok.token_to_id(m) for m in _MODEL_TURNS if tok.token_to_id(m)}
    from .tokenizer.protocol import SPECIAL_TOKENS

    all_marker_ids = {tok.token_to_id(m) for m in SPECIAL_TOKENS
                      if tok.token_to_id(m) is not None}
    pad_id = tok.token_to_id("<|pad|>") or 0

    inputs: list[np.ndarray] = []
    masks: list[np.ndarray] = []

    files = sorted(trajectory_dir.glob("trajectory-*.txt"))
    if not files:
        raise SystemExit(
            f"no trajectories under {trajectory_dir}. Generate them first:\n"
            "    python3 -m training.trajectories --repeats 8"
        )

    for file in files:
        ids = tok.encode(file.read_text(encoding="utf-8")).ids
        if len(ids) < 32:
            continue
        mask = np.zeros(len(ids), dtype=np.int8)
        emitting = False
        for i, tid in enumerate(ids):
            if tid in all_marker_ids:
                emitting = tid in marker_ids
                continue          # the marker itself is context, not output
            if emitting:
                mask[i] = 1

        # Long trajectories are truncated rather than windowed: a window that
        # starts mid-observation trains on a prefix the model would never see.
        ids = ids[:seq_len]
        mask = mask[:seq_len]
        if mask.sum() == 0:
            continue
        pad = seq_len - len(ids)
        if pad > 0:
            ids = np.concatenate([ids, np.full(pad, pad_id, dtype=np.int64)])
            mask = np.concatenate([mask, np.zeros(pad, dtype=np.int8)])
        inputs.append(np.asarray(ids, dtype=np.int64))
        masks.append(np.asarray(mask, dtype=np.int8))

    return np.stack(inputs), np.stack(masks)


def masked_loss(model: Whetstone, ids: mx.array, mask: mx.array) -> mx.array:
    """Cross-entropy over the model's own turns only.

    ``mask`` aligns with the *targets*, so it is sliced one to the right of the
    inputs — the token at position i+1 is what position i is asked to predict.
    """
    logits, _ = model(ids[:, :-1])
    targets = ids[:, 1:]
    target_mask = mask[:, 1:].astype(mx.float32)

    losses = nn.losses.cross_entropy(
        logits.astype(mx.float32).reshape(-1, model.cfg.vocab_size),
        targets.reshape(-1), reduction="none",
    ).reshape(targets.shape)

    total = (losses * target_mask).sum()
    count = mx.maximum(target_mask.sum(), 1.0)
    return total / count


def sft(
    base_checkpoint: Path,
    trajectory_dir: Path,
    tokenizer_path: Path,
    out: Path,
    *,
    epochs: int = 3,
    batch_size: int = 4,
    learning_rate: float = 5e-5,
    seed: int = 1337,
) -> Path:
    """Fine-tune a pretrained checkpoint on trajectories.

    The learning rate is an order of magnitude below pretraining's on purpose.
    A short run at full rate would overwrite the language competence that took
    hours to acquire in order to learn a format that takes minutes — catastrophic
    forgetting, bought for nothing.
    """
    mx.random.seed(seed)
    state = json.loads((base_checkpoint / "state.json").read_text(encoding="utf-8"))
    from .config import ModelConfig

    cfg = ModelConfig(**state["model"])
    model = Whetstone(cfg)
    opt = optim.AdamW(learning_rate=learning_rate, betas=[0.9, 0.95],
                      weight_decay=0.0)
    load_checkpoint(base_checkpoint, model, opt)
    # A fresh optimiser: the pretraining moments describe a different objective
    # at a different learning rate and carrying them in would fight the new one.
    opt = optim.AdamW(learning_rate=learning_rate, betas=[0.9, 0.95],
                      weight_decay=0.0)

    ids_all, mask_all = build_examples(trajectory_dir, tokenizer_path, cfg.max_seq_len)
    n = len(ids_all)
    supervised = int(mask_all.sum())
    print(f"{cfg.name} {cfg.n_params/1e6:.1f}M — resuming from step {state['step']:,}")
    print(f"{n:,} trajectories, {supervised:,} supervised tokens "
          f"({supervised / max(mask_all.size, 1):.1%} of the stream)\n")

    rng = np.random.default_rng(seed)
    steps_per_epoch = max(1, n // batch_size)
    total_steps = steps_per_epoch * epochs
    tcfg = TrainConfig(learning_rate=learning_rate, warmup_ratio=0.05,
                       min_lr_ratio=0.1)

    def loss_fn(m: Whetstone, x: mx.array, msk: mx.array) -> mx.array:
        return masked_loss(m, x, msk)

    grad_fn = nn.value_and_grad(model, loss_fn)
    step = 0
    t0 = time.perf_counter()

    for epoch in range(epochs):
        order = rng.permutation(n)
        for b in range(steps_per_epoch):
            idx = order[b * batch_size:(b + 1) * batch_size]
            if len(idx) == 0:
                continue
            opt.learning_rate = cosine_lr(step, total_steps, tcfg)
            x = mx.array(ids_all[idx])
            m = mx.array(mask_all[idx].astype(np.float32))
            loss, grads = grad_fn(model, x, m)
            grads, gnorm = optim.clip_grad_norm(grads, 1.0)
            opt.update(model, grads)
            mx.eval(model.parameters(), opt.state)
            step += 1
            if step % 20 == 0 or step == 1:
                print(f"epoch {epoch+1}/{epochs}  step {step:>5}/{total_steps}  "
                      f"loss {loss.item():6.3f}  lr {opt.learning_rate.item():.2e}  "
                      f"|g| {float(gnorm):5.2f}", flush=True)

    save_checkpoint(out, model, opt, state["step"] + step, cfg, tcfg)
    print(f"\ndone in {time.perf_counter()-t0:.0f}s -> {out}")
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Fine-tune on agent trajectories.")
    p.add_argument("--checkpoint", type=Path, required=True)
    p.add_argument("--trajectories", type=Path,
                   default=Path("/Volumes/at0m_b0mb/whetstone/corpus/raw/trajectories"))
    p.add_argument("--tokenizer", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--lr", type=float, default=5e-5)
    args = p.parse_args(argv)

    sft(args.checkpoint, args.trajectories, args.tokenizer, args.out,
        epochs=args.epochs, batch_size=args.batch_size, learning_rate=args.lr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
