"""Supervised fine-tuning on agent trajectories.

Pretraining teaches the model the *language* of security. This teaches it the
*job*. They are different curricula and conflating them is why ``action-json``
scored 0/5: the pretraining corpus is 466M characters of security text in which
trajectories would be a rounding error, so diluting one with the other means the
task signal never gets a turn.

Two stages, in order:

1. **Pretrain** on everything. The model learns what a registry path looks like,
   what a CVSS vector is, that YAML nests, that PowerShell is Verb-Noun.
2. **Fine-tune** on trajectories alone, at a low learning rate, for a short run.
   The model learns that a task is answered by emitting ``<|act|>`` with JSON
   the registry accepts, reading ``<|obs|>``, and continuing.

**Loss is masked to the model's own turns.** A trajectory contains the task, the
catalogue, and the observations — none of which the model produces at serving
time. Training it to predict an observation teaches it to hallucinate tool
output, which is the single worst failure mode an agent can have: a model that
writes its own ``<|obs|>`` will confidently report findings about a machine it
never touched. Only the spans after ``<|act|>``, ``<|plan|>`` and ``<|find|>``
carry gradient. Everything else is context to condition on, not output to
imitate.

That masking is the whole reason this file exists rather than being three lines
of pretraining with a different dataset.

**Two consequences of that masking were got wrong, and neither moved the loss
curve.** Once the loss is masked, an example's pull on the gradient is its
*supervised-token* count, not one vote per example — so the replay mixture has
to be sized in supervised tokens (``size_replay``), and sizing it in examples
put a nominal 25% rehearsal at 51% of the objective. And once supervision is
concentrated in particular segments, *where* an over-long trajectory is cut
decides what supervision is lost — so the budget comes out of the observations
the model reads rather than the turns it writes (``_fit_to_budget``), because
head-truncating deleted 95 of the corpus's 405 ``<|find|>`` segments. Both bugs
looked exactly like a model that was too small.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass
from pathlib import Path

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
import numpy as np

from .config import TrainConfig
from .model import Whetstone
from .pretrain import cosine_lr, load_checkpoint, save_checkpoint

__all__ = [
    "ExampleStats", "build_examples", "replay_share", "sft", "size_replay",
    "supervised_targets",
]

_FINDING = "<|find|>"
#: Segments whose content the model is responsible for producing. Everything
#: else in a trajectory is given to it, not generated by it.
_MODEL_TURNS = ("<|act|>", "<|plan|>", _FINDING)

#: The one segment that is pure context *and* carries most of the length: a
#: trajectory averages 570 observation tokens against 69 supervised ones. It is
#: therefore the only thing a trajectory gives up when it does not fit.
_OBSERVATION = "<|obs|>"

#: What an over-budget observation's payload is replaced with. Valid JSON,
#: because the model reads observations as JSON and a half-cut object would
#: teach it that they can arrive malformed; and *marked*, because
#: ``render.shrink_payload`` already established the rule that a cut says where
#: it cut — a silently shortened observation teaches the model that hosts have
#: four services, a marked one teaches it that it is reading a summary.
_ELIDED_PAYLOAD = '{"elided":true}'

#: Said in two places (the argument check and the sizer), so it is written once.
_BAD_FRACTION = (
    "replay_fraction must be in [0, 1); got {fraction!r}. It is a share of the "
    "training objective, so 1.0 asks for a fine-tune with no trajectories in it."
)


@dataclass(frozen=True, slots=True)
class ExampleStats:
    """What ``build_examples`` had to do to the corpus, in countable units.

    Returned rather than printed from inside the builder because a number a test
    can assert on is the only kind that stays true. ``finding_turns`` is here
    specifically because the truncation bug was invisible: the run printed one
    combined supervised-token total, that total was only 7% short, and nearly a
    quarter of the findings had been deleted.
    """

    seq_len: int
    trajectories: int
    #: Supervised *targets*, counted the way :func:`masked_loss` counts them.
    supervised: int
    #: ``<|find|>`` markers surviving in the kept examples.
    finding_turns: int
    elided_trajectories: int
    elided_observations: int
    dropped_over_length: int
    dropped_unsupervised: int
    skipped_short: int

    def report(self) -> str:
        lines = [
            (f"{self.trajectories:,} trajectories, {self.supervised:,} "
             f"supervised tokens, {self.finding_turns:,} <|find|> turns")
        ]
        if self.elided_trajectories:
            lines.append(
                f"  {self.elided_trajectories:,} over {self.seq_len:,} tokens: "
                f"{self.elided_observations:,} observation payloads elided so "
                f"their act/plan/find turns survive")
        if self.dropped_over_length:
            lines.append(
                f"  {self.dropped_over_length:,} DROPPED — their own turns alone "
                f"exceed {self.seq_len:,} tokens; raise max_seq_len rather than "
                f"training on half an episode")
        if self.dropped_unsupervised:
            lines.append(
                f"  {self.dropped_unsupervised:,} DROPPED — no model turn in "
                f"them to learn from")
        if self.skipped_short:
            lines.append(f"  {self.skipped_short:,} skipped — under 32 tokens")
        return "\n".join(lines)


def _segments(
    ids: list[int], all_marker_ids: set[int]
) -> list[tuple[int | None, int, int]]:
    """Split a token stream into ``(marker_id, start, end)`` runs.

    Every segment begins at a protocol marker and runs to the next one, which is
    the same walk the loss mask does — done once here so the budgeting below and
    the mask cannot disagree about where a turn starts. Text before the first
    marker gets ``None`` and is never touched: a trajectory always opens with
    ``<|bos|>`` so this should be empty, and if it is not, whatever it is is not
    something this function is entitled to elide.
    """
    starts = [i for i, tid in enumerate(ids) if tid in all_marker_ids]
    if not starts:
        return [(None, 0, len(ids))]
    segments: list[tuple[int | None, int, int]] = []
    if starts[0] != 0:
        segments.append((None, 0, starts[0]))
    for start, nxt in zip(starts, [*starts[1:], len(ids)]):
        segments.append((ids[start], start, nxt))
    return segments


def _mask_model_turns(
    ids: list[int], model_turn_ids: set[int], all_marker_ids: set[int]
) -> np.ndarray:
    """1 at every position the model is responsible for producing, 0 elsewhere.

    Built by walking the token stream and flipping on at a model-turn marker,
    off at the next marker of any kind. Doing it in token space rather than
    character space avoids an off-by-one where a marker's own tokens fall on the
    wrong side of the boundary — which would train the model to predict the
    marker that *precedes* its turn instead of the content that follows it.
    """
    mask = np.zeros(len(ids), dtype=np.int8)
    emitting = False
    for i, tid in enumerate(ids):
        if tid in all_marker_ids:
            emitting = tid in model_turn_ids
            continue          # the marker itself is context, not output
        if emitting:
            mask[i] = 1
    return mask


def _fit_to_budget(
    ids: list[int],
    seq_len: int,
    *,
    obs_id: int,
    elide_ids: list[int],
    all_marker_ids: set[int],
) -> tuple[list[int], int] | None:
    """Make a trajectory fit ``seq_len`` by eliding observations, oldest first.

    Head truncation (``ids[:seq_len]``) is the obvious thing and it is precisely
    the wrong thing. ``render_episode`` appends every ``<|find|>`` segment after
    the last observation, so a finding is structurally the *last* thing in a
    trajectory and a head cut therefore deletes the rarest and most valuable
    model turn first. Measured over the whole 1,250-file corpus at
    ``seq_len=1024``: 22% of trajectories are over budget, and 95 of the 405
    findings in it — 23% — never reach the model. Nothing refused those
    examples, because they still had plenty of ``<|act|>`` supervision inside
    the window and so passed the ``mask.sum() == 0`` guard; and the total
    supervised-token count was short by only 7%, so the run printed a healthy
    number while a quarter of the findings went in the bin. The model then
    under-produces findings at serving time, which reads as a model that has not
    learned to report detection gaps: a conclusion about capacity drawn from a
    slicing rule.

    So the budget is taken out of what the model *reads* rather than what it
    *writes*. Observation payloads are replaced with :data:`_ELIDED_PAYLOAD`,
    keeping the ``<|obs|>`` marker itself so the act/obs alternation the model
    sees at serving time survives intact. Oldest first, because the last
    observation is the one the closing action and the finding are reasoning
    from; and one whole payload at a time rather than a partial cut, because
    half an observation is invalid JSON and only whole-object elision keeps the
    format the model is being taught to parse.

    Returns the fitted ids and how many observations had to go, or ``None`` when
    even eliding every observation does not fit — which means the model's own
    turns plus the protocol header exceed the context window, and there is no
    honest way to train on that example at this ``seq_len``. The caller counts
    those and prints the count rather than dropping them quietly.
    """
    if len(ids) <= seq_len:
        return list(ids), 0

    segments = _segments(ids, all_marker_ids)
    parts = [list(ids[start:end]) for _, start, end in segments]
    total = len(ids)
    elided = 0

    for i, (marker, start, end) in enumerate(segments):
        if total <= seq_len:
            break
        if marker != obs_id:
            continue
        shrunk = [ids[start], *elide_ids]        # the marker, then the notice
        if len(shrunk) >= end - start:
            continue          # this observation is already shorter than its own
                              # replacement; eliding it would add tokens
        total -= (end - start) - len(shrunk)
        parts[i] = shrunk
        elided += 1

    if total > seq_len:
        return None
    return [tid for part in parts for tid in part], elided


def build_examples(
    trajectory_dir: Path, tokenizer_path: Path, seq_len: int
) -> tuple[np.ndarray, np.ndarray, ExampleStats]:
    """Tokenise trajectories into (inputs, loss_mask, stats) padded to ``seq_len``.

    The mask covers the model's own turns only (:func:`_mask_model_turns`) and
    over-long trajectories give up observations rather than their conclusions
    (:func:`_fit_to_budget`). The third return value is what those two decisions
    cost, in counts, so the caller can print it — every earlier version of this
    function made those decisions silently.
    """
    from tokenizers import Tokenizer

    tok = Tokenizer.from_file(str(tokenizer_path))

    # ``is not None``, not truthiness. Token id 0 is a legal id, and the earlier
    # ``if tok.token_to_id(m)`` here would have dropped a marker that landed on
    # id 0 from the mask — an entire class of model turn supervised nowhere,
    # with no error and a loss curve that still falls.
    required = (*_MODEL_TURNS, _OBSERVATION, "<|pad|>")
    missing = [m for m in required if tok.token_to_id(m) is None]
    if missing:
        raise SystemExit(
            f"{tokenizer_path} does not carry {', '.join(missing)} as atomic "
            "ids. The loss mask is built by walking to those ids, so a "
            "tokenizer without them would train on nothing at all, or on "
            "everything including the observations. Retrain it with "
            "training.tokenizer, which feeds SPECIAL_TOKENS to the BPE trainer."
        )

    from .tokenizer.protocol import SPECIAL_TOKENS

    model_turn_ids = {tok.token_to_id(m) for m in _MODEL_TURNS}
    all_marker_ids = {tok.token_to_id(m) for m in SPECIAL_TOKENS
                      if tok.token_to_id(m) is not None}
    obs_id = tok.token_to_id(_OBSERVATION)
    find_id = tok.token_to_id(_FINDING)
    pad_id = tok.token_to_id("<|pad|>")
    # Encoded once. It carries no marker of its own, so an elided observation
    # stays one segment and the mask walk sees exactly what it saw before.
    elide_ids = list(tok.encode(_ELIDED_PAYLOAD).ids)

    inputs: list[np.ndarray] = []
    masks: list[np.ndarray] = []
    finding_turns = 0
    elided_trajectories = elided_observations = 0
    dropped_over_length = dropped_unsupervised = skipped_short = 0

    files = sorted(trajectory_dir.glob("trajectory-*.txt"))
    if not files:
        raise SystemExit(
            f"no trajectories under {trajectory_dir}. Generate them first:\n"
            "    python3 -m training.trajectories --repeats 8"
        )

    for file in files:
        ids = list(tok.encode(file.read_text(encoding="utf-8")).ids)
        if len(ids) < 32:
            skipped_short += 1
            continue

        fitted = _fit_to_budget(ids, seq_len, obs_id=obs_id,
                                elide_ids=elide_ids,
                                all_marker_ids=all_marker_ids)
        if fitted is None:
            dropped_over_length += 1
            continue
        ids, n_elided = fitted

        mask = _mask_model_turns(ids, model_turn_ids, all_marker_ids)
        if mask.sum() == 0:
            dropped_unsupervised += 1
            continue
        # Counted only once the example is known to be kept, so the elision
        # totals describe the corpus that gets trained on rather than the work
        # done to arrive at it.
        if n_elided:
            elided_trajectories += 1
            elided_observations += n_elided
        finding_turns += sum(1 for tid in ids if tid == find_id)

        pad = seq_len - len(ids)
        if pad > 0:
            ids = np.concatenate([ids, np.full(pad, pad_id, dtype=np.int64)])
            mask = np.concatenate([mask, np.zeros(pad, dtype=np.int8)])
        inputs.append(np.asarray(ids, dtype=np.int64))
        masks.append(np.asarray(mask, dtype=np.int8))

    if not inputs:
        raise SystemExit(
            f"every trajectory under {trajectory_dir} was dropped: "
            f"{dropped_over_length:,} longer than {seq_len:,} tokens even with "
            f"their observations elided, {dropped_unsupervised:,} with no model "
            f"turn, {skipped_short:,} under 32 tokens. There is nothing to "
            "fine-tune on — check the tokenizer matches the checkpoint."
        )

    ids_all = np.stack(inputs)
    mask_all = np.stack(masks)
    stats = ExampleStats(
        seq_len=seq_len,
        trajectories=len(inputs),
        supervised=supervised_targets(mask_all),
        finding_turns=finding_turns,
        elided_trajectories=elided_trajectories,
        elided_observations=elided_observations,
        dropped_over_length=dropped_over_length,
        dropped_unsupervised=dropped_unsupervised,
        skipped_short=skipped_short,
    )
    return ids_all, mask_all, stats


def supervised_targets(mask: np.ndarray) -> int:
    """Count the positions :func:`masked_loss` will actually take a gradient at.

    The first column is dropped because the loss aligns the mask with the
    *targets* (``mask[:, 1:]``): position 0 has no predecessor to predict it, so
    a 1 there is supervision that never happens. The replay mixture below is
    budgeted in these units, so this counter and the loss have to agree exactly
    or the ratio being enforced is not the ratio the optimiser sees.
    """
    return int(mask[..., 1:].sum())


def masked_loss(model: Whetstone, ids: mx.array, mask: mx.array) -> mx.array:
    """Cross-entropy over the model's own turns only.

    ``mask`` aligns with the *targets*, so it is sliced one to the right of the
    inputs — the token at position i+1 is what position i is asked to predict.

    **The divisor is what sets the mixture.** It is *this batch's* supervised
    token count, so within a step an example pulls in proportion to its share of
    that step's supervised tokens, and across steps every batch contributes the
    same amount regardless of how many supervised tokens it held. That is the
    standard normalisation and it is kept — it is what keeps the gradient norm
    comparable across wildly uneven batches — but it means the share of the
    objective a population of examples carries is the *mean over batches* of its
    token share in each, which is neither its share of the examples nor its
    share of all supervised tokens. :func:`replay_share` computes that quantity
    exactly and :func:`size_replay` solves for it.
    """
    logits, _ = model(ids[:, :-1])
    targets = ids[:, 1:]
    target_mask = mask[:, 1:].astype(mx.float32)

    losses = nn.losses.cross_entropy(
        logits.astype(mx.float32).reshape(-1, model.cfg.vocab_size),
        targets.reshape(-1), reduction="none",
    ).reshape(targets.shape)

    total = (losses * target_mask).sum()
    count = mx.maximum(target_mask.sum(), 1.0)
    return total / count


def load_replay(shard_dir: Path, seq_len: int, n: int, seed: int) -> np.ndarray:
    """Sample ``n`` windows of pretraining text, to rehearse against forgetting.

    **Measured, not precautionary.** Fine-tuning on trajectories alone took
    ``cvss-vector`` from 3/5 to 0/10 while taking ``action-json`` from 0/5 to
    5/10. The model traded schema knowledge for the task, because trajectories
    contain no CVSS vectors and four epochs of gradient on text that never
    mentions one is enough to lose it at this scale.

    Mixing pretraining windows back in is the standard remedy and it is cheap:
    the shards are already on disk and memory-mapped. These windows carry
    ordinary next-token loss over their whole length — there is no "model turn"
    in a man page — which is why the sampler returns ids only and the trainer
    supplies an all-ones mask for them. That all-ones mask is also why they
    cannot be counted like trajectories: one window supervises ``seq_len - 1``
    targets where a trajectory supervises about seventy.
    """
    from .data import Dataset

    data = Dataset(shard_dir, seq_len, split="train", seed=seed)
    x, _y = data.batch(n)
    return np.asarray(x, dtype=np.int64)


def replay_share(
    traj_targets: np.ndarray,
    n_replay: int,
    per_window: int,
    *,
    batch_size: int,
    epochs: int,
    seed: int,
) -> float:
    """The share of the training objective ``n_replay`` windows will carry.

    Not an estimate. :func:`sft` shuffles with ``np.random.default_rng(seed)``
    and cuts each epoch's permutation into fixed-size batches, so the batches
    this run will actually see can be dealt out here before a single step is
    taken, and the answer is the realised number rather than a prediction.

    The quantity: :func:`masked_loss` divides each batch by that batch's own
    supervised-token count, so the objective being minimised is the mean over
    steps of a per-batch token mean, and the replay part of it is the mean over
    batches of (replay targets in the batch / all targets in the batch). Two
    simpler-looking answers are both wrong, and each was wrong in a different
    direction:

    * **Share of examples** — what the code did. 25% of 1,250 trajectories is
      312 windows, each supervising 1,023 targets against a trajectory's ~69,
      so replay took 79% of the supervised tokens and 51% of the objective
      while the log printed "(25%)". The module docstring's whole premise, that
      the task signal never gets a turn when it is diluted, was being violated
      by the code meant to prevent it.
    * **Share of all supervised tokens** — the obvious correction, and it
      undershoots by the same mechanism in reverse. 28 windows make replay 25%
      of the supervised tokens in the corpus, but those 1,023-target windows
      land in 28 batches out of 319 and per-batch normalisation caps what any
      one batch can contribute, so replay ends up at 7% of the objective. The
      answer that is actually 25% of it is 114 windows, between the two.
    """
    if n_replay <= 0:
        return 0.0
    counts = np.concatenate([
        np.asarray(traj_targets, dtype=np.float64),
        np.full(n_replay, float(per_window)),
    ])
    is_replay = np.concatenate([
        np.zeros(len(traj_targets)), np.ones(n_replay),
    ])
    n = len(counts)
    steps = max(1, n // batch_size)
    rng = np.random.default_rng(seed)
    shares: list[np.ndarray] = []
    for _ in range(epochs):
        # The same draw sequence as the training loop: one permutation per
        # epoch from one generator seeded once. A fresh generator is used here
        # so that asking the question does not move the trainer's own stream.
        order = rng.permutation(n)[:steps * batch_size].reshape(steps, batch_size)
        totals = counts[order].sum(axis=1)
        replayed = (counts[order] * is_replay[order]).sum(axis=1)
        shares.append(np.divide(replayed, totals, out=np.zeros_like(totals),
                                where=totals > 0))
    return float(np.concatenate(shares).mean())


def size_replay(
    traj_targets: np.ndarray,
    fraction: float,
    per_window: int,
    *,
    batch_size: int,
    epochs: int,
    seed: int,
) -> int:
    """How many pretraining windows make replay ``fraction`` of the objective.

    Searched rather than derived. The share is monotone in the window count but
    not smooth in it — a window either lands in a batch or does not — so a
    closed form would be an approximation with no way to check itself, whereas
    :func:`replay_share` can simply be asked, and the candidate whose realised
    share is closest to what was requested wins. The search costs a few dozen
    permutations of an integer array, which is nothing next to one training
    step, and it happens before the first one.
    """
    if not 0.0 <= fraction < 1.0:
        raise ValueError(_BAD_FRACTION.format(fraction=fraction))
    if fraction == 0.0 or len(traj_targets) == 0:
        return 0

    def share(n: int) -> float:
        return replay_share(traj_targets, n, per_window, batch_size=batch_size,
                            epochs=epochs, seed=seed)

    # A ceiling so a fraction the window size cannot reach terminates anyway;
    # the caller prints the realised share, so an unreachable ask is visible
    # rather than silently rounded to something else.
    cap = max(1, 16 * len(traj_targets))
    lo, hi = 0, 1
    while hi < cap and share(hi) < fraction:
        lo, hi = hi, min(cap, hi * 2)

    best, best_err = hi, abs(share(hi) - fraction)
    while lo < hi:
        mid = (lo + hi) // 2
        err = abs(share(mid) - fraction)
        if err < best_err:
            best, best_err = mid, err
        if share(mid) < fraction:
            lo = mid + 1
        else:
            hi = mid
    return best


def sft(
    base_checkpoint: Path,
    trajectory_dir: Path,
    tokenizer_path: Path,
    out: Path,
    *,
    epochs: int = 3,
    batch_size: int = 4,
    learning_rate: float = 5e-5,
    seed: int = 1337,
    replay_dir: Path | None = None,
    replay_fraction: float = 0.25,
) -> Path:
    """Fine-tune a pretrained checkpoint on trajectories.

    The learning rate is an order of magnitude below pretraining's on purpose.
    A short run at full rate would overwrite the language competence that took
    hours to acquire in order to learn a format that takes minutes — catastrophic
    forgetting, bought for nothing.

    ``replay_fraction`` is a share of the **training objective**, not of the
    example count: see :func:`replay_share` for why those differ by a factor of
    three in either direction, and why the realised share is printed.
    """
    # Checked before a checkpoint is loaded: a typo'd knob should cost a second,
    # not the minute it takes to read weights off the disk first.
    if not 0.0 <= replay_fraction < 1.0:
        raise ValueError(_BAD_FRACTION.format(fraction=replay_fraction))

    mx.random.seed(seed)
    state = json.loads((base_checkpoint / "state.json").read_text(encoding="utf-8"))
    from .config import ModelConfig

    cfg = ModelConfig(**state["model"])
    model = Whetstone(cfg)
    opt = optim.AdamW(learning_rate=learning_rate, betas=[0.9, 0.95],
                      weight_decay=0.0)
    load_checkpoint(base_checkpoint, model, opt)
    # A fresh optimiser: the pretraining moments describe a different objective
    # at a different learning rate and carrying them in would fight the new one.
    opt = optim.AdamW(learning_rate=learning_rate, betas=[0.9, 0.95],
                      weight_decay=0.0)

    ids_all, mask_all, stats = build_examples(
        trajectory_dir, tokenizer_path, cfg.max_seq_len)
    print(f"{cfg.name} {cfg.n_params/1e6:.1f}M — resuming from step {state['step']:,}")
    print(stats.report())

    # Replay: rehearse pretraining text so the task does not cost the language.
    # Sized in supervised tokens as they reach the objective, never in examples.
    traj_targets = mask_all[:, 1:].sum(axis=1)
    per_window = cfg.max_seq_len - 1          # the mask loses position 0
    if replay_dir is not None and replay_fraction > 0:
        n_replay = size_replay(traj_targets, replay_fraction, per_window,
                               batch_size=batch_size, epochs=epochs, seed=seed)
        if n_replay:
            realised = replay_share(traj_targets, n_replay, per_window,
                                    batch_size=batch_size, epochs=epochs,
                                    seed=seed)
            replay_ids = load_replay(replay_dir, cfg.max_seq_len, n_replay, seed)
            # An all-ones mask: every token of a man page is the model's to
            # predict. There is no "turn" to mask in pretraining text.
            replay_mask = np.ones_like(replay_ids, dtype=np.int8)
            ids_all = np.concatenate([ids_all, replay_ids])
            mask_all = np.concatenate([mask_all, replay_mask])
            print(f"replay: {n_replay:,} pretraining windows × {per_window:,} "
                  f"supervised tokens against {stats.supervised:,} from "
                  f"trajectories — {realised:.1%} of the objective, "
                  f"{replay_fraction:.0%} asked for")
        else:
            print(f"replay: NONE — one {per_window:,}-token window would "
                  f"already take more than {replay_fraction:.0%} of the "
                  f"objective from {stats.supervised:,} supervised trajectory "
                  f"tokens. Rehearsal is off for this run.")
    print()

    n = len(ids_all)
    rng = np.random.default_rng(seed)
    steps_per_epoch = max(1, n // batch_size)
    total_steps = steps_per_epoch * epochs
    tcfg = TrainConfig(learning_rate=learning_rate, warmup_ratio=0.05,
                       min_lr_ratio=0.1)

    def loss_fn(m: Whetstone, x: mx.array, msk: mx.array) -> mx.array:
        return masked_loss(m, x, msk)

    grad_fn = nn.value_and_grad(model, loss_fn)
    step = 0
    t0 = time.perf_counter()

    for epoch in range(epochs):
        order = rng.permutation(n)
        for b in range(steps_per_epoch):
            idx = order[b * batch_size:(b + 1) * batch_size]
            if len(idx) == 0:
                continue
            opt.learning_rate = cosine_lr(step, total_steps, tcfg)
            x = mx.array(ids_all[idx])
            m = mx.array(mask_all[idx].astype(np.float32))
            loss, grads = grad_fn(model, x, m)
            grads, gnorm = optim.clip_grad_norm(grads, 1.0)
            opt.update(model, grads)
            mx.eval(model.parameters(), opt.state)
            step += 1
            if step % 20 == 0 or step == 1:
                print(f"epoch {epoch+1}/{epochs}  step {step:>5}/{total_steps}  "
                      f"loss {loss.item():6.3f}  lr {opt.learning_rate.item():.2e}  "
                      f"|g| {float(gnorm):5.2f}", flush=True)

    save_checkpoint(out, model, opt, state["step"] + step, cfg, tcfg)
    print(f"\ndone in {time.perf_counter()-t0:.0f}s -> {out}")
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Fine-tune on agent trajectories.")
    p.add_argument("--checkpoint", type=Path, required=True)
    p.add_argument("--trajectories", type=Path,
                   default=Path("/Volumes/at0m_b0mb/whetstone/corpus/raw/trajectories"))
    p.add_argument("--tokenizer", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--lr", type=float, default=5e-5)
    p.add_argument("--replay", type=Path,
                   help="pretraining shard dir to rehearse from; strongly "
                        "advised — without it cvss-vector fell 3/5 to 0/10")
    p.add_argument("--replay-fraction", type=float, default=0.25,
                   help="share of the training OBJECTIVE that rehearsal gets, "
                        "not a share of the examples; the realised number is "
                        "printed at startup")
    args = p.parse_args(argv)

    sft(args.checkpoint, args.trajectories, args.tokenizer, args.out,
        epochs=args.epochs, batch_size=args.batch_size, learning_rate=args.lr,
        replay_dir=args.replay, replay_fraction=args.replay_fraction)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
