"""Capture a real run to committable artifacts — the model, on the record.

Runs the trained model against a lab target for real and writes three files that
together are an honest record of what happened:

* ``<name>.trajectory.txt`` — the wire protocol, byte for byte. This is the
  training-data format, so the file doubles as a worked example of what a
  trajectory looks like and as proof that a real run produces valid training
  data with no conversion step.
* ``<name>.transcript.md`` — the same run for a human: each action, the real
  observation it returned, and the findings, with the model's own runner-up
  choices shown so its judgement is legible rather than a black box.
* ``<name>.findings.json`` — the machine-readable result: the detection gaps and
  what produced them.

Nothing here is illustrative or edited. The observations are what the adapter
actually returned from the actual target on this machine, captured at the
timestamp in the header. Regenerate on a different host and the observations
change, because they are observations.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from whetstone.kernel import Episode
from whetstone.kernel.render import render_episode, shrink_payload

__all__ = ["capture", "CaptureMeta"]


@dataclass(frozen=True, slots=True)
class CaptureMeta:
    """Provenance for a captured run, so the artifact is reproducible."""

    checkpoint: str
    target: str
    telemetry: str
    timestamp: str
    driver: str          # "trained model (constrained decoding)" | "scripted" | ...


def _transcript(episode: Episode, meta: CaptureMeta, decisions: list[dict]) -> str:
    lines = [
        f"# Whetstone run — {meta.target}",
        "",
        "> A real run, captured verbatim. The observations are what the adapter",
        "> returned from the actual target; nothing here is illustrative.",
        "",
        "| | |",
        "|---|---|",
        f"| driver | {meta.driver} |",
        f"| checkpoint | `{meta.checkpoint}` |",
        f"| target | {meta.target} |",
        f"| telemetry | {meta.telemetry} |",
        f"| captured | {meta.timestamp} |",
        "",
        f"**Task** — {episode.task}",
        "",
        f"**Result** — {len(episode.turns)} turns, "
        f"{episode.observations} observations, {episode.refusals} refusals, "
        f"**{len(episode.findings)} findings**.",
        "",
        "---",
        "",
        "## The run, turn by turn",
        "",
    ]

    decision_by_i = {d["turn"]: d for d in decisions}
    for i, turn in enumerate(episode.turns):
        verdict = ("REFUSED" if turn.refused else
                   "ok" if turn.succeeded else "failed")
        lines.append(f"### {i + 1}. `{turn.action.render()}` — {verdict}")

        d = decision_by_i.get(i)
        if d and d.get("alternatives"):
            alts = ", ".join(f"`{a}`" for a in d["alternatives"][:3])
            lines.append(f"*model chose this over: {alts}*")

        if turn.refused:
            lines += ["", "```", f"{turn.decision.rule}: {turn.decision.reason}",
                      "```", ""]
            continue

        if turn.observation is not None and turn.observation.data is not None:
            payload = shrink_payload(turn.observation.data)
            lines += ["", "```json",
                      json.dumps(payload, indent=2, ensure_ascii=False)[:900],
                      "```", ""]
        elif turn.observation is not None and turn.observation.unsupported:
            lines += ["", f"_unsupported: {turn.observation.error}_", ""]

    if episode.findings:
        lines += ["---", "", "## Findings", ""]
        for f in episode.findings:
            head = {"detection_gap": "🔴 DETECTION GAP",
                    "no_coverage": "⚪ NO COVERAGE",
                    "observation": "🟡 INCONCLUSIVE"}.get(f.kind, f.kind)
            lines.append(f"- **{head}** — `{f.technique}` — {f.detail}")

    lines += ["", "---", "",
              "*Generated by `lab/capture.py`. "
              "Reproduce with the command in the run's header comment.*"]
    return "\n".join(lines) + "\n"


def capture(
    episode: Episode, meta: CaptureMeta, out_dir: Path, name: str,
    *, decisions: list[dict] | None = None,
) -> dict[str, Path]:
    """Write the three artifacts and return their paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    decisions = decisions or []

    traj = out_dir / f"{name}.trajectory.txt"
    traj.write_text(render_episode(episode), encoding="utf-8")

    md = out_dir / f"{name}.transcript.md"
    md.write_text(_transcript(episode, meta, decisions), encoding="utf-8")

    findings = out_dir / f"{name}.findings.json"
    findings.write_text(json.dumps({
        "meta": {"checkpoint": meta.checkpoint, "target": meta.target,
                 "telemetry": meta.telemetry, "captured": meta.timestamp,
                 "driver": meta.driver, "task": episode.task},
        "turns": len(episode.turns),
        "observations": episode.observations,
        "refusals": episode.refusals,
        "findings": [f.to_dict() for f in episode.findings],
    }, indent=2, ensure_ascii=False), encoding="utf-8")

    return {"trajectory": traj, "transcript": md, "findings": findings}
